version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: propelize
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build: .
    container_name: node-app
    depends_on:
      - db
    ports:
      - "8080:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: propelize
    command: sh -c "npx sequelize-cli db:migrate && npm start"
    env_file:
      - .env

volumes:
  mysql-data:
