name: CI Propelize Front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Lint backend (si ESLint installé)
      - name: Lint backend
        run: npx eslint . || echo "Pas de linter backend configuré"
        working-directory: ./backend

      # 4. Lint frontend (si ESLint installé)
      - name: Lint frontend
        run: npx eslint . || echo "Pas de linter frontend configuré"
        working-directory: ./frontend

      # 5. Exécuter les tests backend (Vitest/Jest)
      - name: Run backend tests
        run: npm test
        working-directory: ./backend

      # 6. Installer les dépendances backend (Express)
      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      # 7. Lancer le serveur Express en tâche de fond
      - name: Start Express server
        run: npm start &
        working-directory: ./backend

      # 8. Attendre que le serveur Express soit prêt
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000
        working-directory: ./backend

      # 9. Installer les dépendances frontend (Playwright)
      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      # 10. Installer les navigateurs Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      # 11. Lancer les tests Playwright (avec BASE_URL pour cibler le backend Express)
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend
        env:
          BASE_URL: http://localhost:3000
